"""initial schema: person + transaction (Block 1)

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-31

Data model per architecture PHASE-2.3 (Data Model & Ledger Design) and
PHASE-2.6 (Persistence, Migrations, Idempotency).

Block 1 scope: structure only. No signed_effect, balance, or correction-apply
logic. This migration is hand-written (not autogenerated) so it is fully
reviewable and can rebuild the schema from scratch (PHASE-2.6 §15).

Note: transaction.superseded_by_id is UNIQUE (linear, non-forking correction
chain). Deferred hardening -- cycle prevention and append-only enforcement
against direct UPDATE/DELETE -- is tracked in docs/decisions/block-1-followups.md.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native PostgreSQL ENUM types. Labels are the exact stored values.
# create_type=False: this migration manages their lifecycle explicitly
# (create at the top of upgrade, drop at the bottom of downgrade) so that
# op.create_table() does NOT also try to emit CREATE TYPE.
event_type = postgresql.ENUM(
    "mama_entrega_dinero",
    "erick_gasta_para_mama",
    "erick_entrega_dinero",
    "mama_devuelve",
    "erick_devuelve",
    name="event_type",
    create_type=False,
)
transaction_status = postgresql.ENUM(
    "ACTIVE", "SUPERSEDED", name="transaction_status", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    event_type.create(bind, checkfirst=True)
    transaction_status.create(bind, checkfirst=True)

    op.create_table(
        "person",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_user_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Short semantic names: the MetaData naming convention (wired through
        # env.py) expands "ck" -> "ck_<table>_<name>".
        sa.CheckConstraint(
            "length(btrim(telegram_user_id)) > 0",
            name="telegram_user_id_not_blank",
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name="name_not_blank"),
        sa.PrimaryKeyConstraint("id", name="pk_person"),
        sa.UniqueConstraint("telegram_user_id", name="uq_person_telegram_user_id"),
    )

    op.create_table(
        "transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", event_type, nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            transaction_status,
            server_default=sa.text("'ACTIVE'::transaction_status"),
            nullable=False,
        ),
        sa.Column("superseded_by_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Short semantic names -> expanded to "ck_transaction_<name>" by the
        # MetaData naming convention.
        sa.CheckConstraint("amount > 0", name="amount_positive"),
        sa.CheckConstraint(
            "length(btrim(description)) > 0",
            name="description_not_blank",
        ),
        sa.CheckConstraint(
            "length(btrim(idempotency_key)) > 0",
            name="idempotency_key_not_blank",
        ),
        sa.CheckConstraint(
            "superseded_by_id IS NULL OR superseded_by_id <> id",
            name="no_self_supersede",
        ),
        sa.CheckConstraint(
            "(status = 'ACTIVE'::transaction_status AND superseded_by_id IS NULL) "
            "OR (status = 'SUPERSEDED'::transaction_status AND superseded_by_id IS NOT NULL)",
            name="status_supersede_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["person.id"],
            name="fk_transaction_created_by_id_person",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["transaction.id"],
            name="fk_transaction_superseded_by_id_transaction",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_transaction"),
        sa.UniqueConstraint("idempotency_key", name="uq_transaction_idempotency_key"),
        # One correction replaces exactly one prior row -> no forked chains.
        # NULLs are distinct in PostgreSQL, so ACTIVE rows are unaffected.
        sa.UniqueConstraint(
            "superseded_by_id", name="uq_transaction_superseded_by_id"
        ),
    )
    op.create_index("ix_transaction_status", "transaction", ["status"])
    op.create_index("ix_transaction_event_date", "transaction", ["event_date"])
    op.create_index("ix_transaction_created_by_id", "transaction", ["created_by_id"])


def downgrade() -> None:
    op.drop_index("ix_transaction_created_by_id", table_name="transaction")
    op.drop_index("ix_transaction_event_date", table_name="transaction")
    op.drop_index("ix_transaction_status", table_name="transaction")
    op.drop_table("transaction")
    op.drop_table("person")
    bind = op.get_bind()
    transaction_status.drop(bind, checkfirst=True)
    event_type.drop(bind, checkfirst=True)
